In [6]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

### Q1.     A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.

In [7]:
cutlets=pd.read_csv('C:/Users/admin/Desktop/ExcelR/Data Science ass/Hypo test/Cutlets.csv')

In [8]:
cutlets.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [11]:
# separating both the columns in different names
# TWO sample TWO tail test

c1=cutlets.iloc[:,0]
c1

c2=cutlets.iloc[:,1]
c2

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [12]:
c1

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [14]:
stats.ttest_ind(c1,c2)

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [17]:
p_value=(stats.ttest_ind(c1,c2)[1])

In [18]:
p_value

0.4722394724599501

In [ ]:
# compare p_value with α = 0.05 (At 5% significance level)
# p_> a , hence accepting NULL Hypothesis

### Q2.A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
  

In [19]:
lab=pd.read_csv('C:/Users/admin/Desktop/ExcelR/Data Science ass/Hypo test/LabTAT.csv')

In [20]:
lab.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [21]:
# separating the columns 

l1=lab.iloc[:,0]
l1

l2=lab.iloc[:,1]
l2

l3=lab.iloc[:,2]
l3

l4=lab.iloc[:,3]
l4

0      166.13
1      160.79
2      185.18
3      176.42
4      152.60
        ...  
115    172.68
116    177.64
117    170.27
118    150.87
119    162.21
Name: Laboratory 4, Length: 120, dtype: float64

In [23]:
# Using ANNOVA method because the data has more than two groups 

stats.f_oneway(l1,l2,l3,l4)

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [24]:
p_value=stats.f_oneway(l1,l2,l3,l4)[1]

In [25]:
p_value

2.1156708949992414e-57

In [ ]:
# compare p_value with α = 0.05 (At 5% significance level)
# p_< a , hence rejecting NULL Hypothesis

### Q3.Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

In [26]:
df=pd.read_csv('C:/Users/admin/Desktop/ExcelR/Data Science ass/Hypo test/BuyerRatio.csv')

In [27]:
df.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [32]:
dff=df.iloc[:,1:]

In [33]:
dff

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [34]:
dff.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [38]:
# here two qualitative variables are independent so we are using chi-square test.

from scipy.stats import chi2_contingency

In [37]:
chi_val, p_val, dof, expected =  chi2_contingency(dff)
chi_val, p_val, dof, expected

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [39]:
chi_val

1.595945538661058

In [41]:
p_val

0.6603094907091882

In [42]:
# degree of freedom
dof

3

In [44]:
# Expected value
expected 

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [47]:
# Critical Value
from scipy.stats import chi2
critical_value=chi2.ppf(0.95,df=3)
critical_value

7.814727903251179

In [ ]:
# compare p_value with α = 0.05 
# p_> a , hence accept NULL Hypothesis

In [50]:
if p_val <= 0.05:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

Independent (fail to reject H0)


### Q4.     TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences


In [53]:
tele=pd.read_csv('C:/Users/admin/Desktop/ExcelR/Data Science ass/Hypo test/Costomer+OrderForm.csv')

In [54]:
tele.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [55]:
tele.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [56]:
tele.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [57]:
tele.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [58]:
tele.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [59]:
TELE=np.array([[271,267,269,280],[29,33,31,20]])

In [60]:
TELE

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [61]:
chi_val, p_val, dof, expected =  chi2_contingency(TELE)
chi_val, p_val, dof, expected

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [62]:
p_val

0.2771020991233135

In [ ]:
# compare p_value with α = 0.05 
# p_> a , hence accept NULL Hypothesis